# site properties and page defaults
title: Data Management and Mining Lab
subtitle: University at Albany - SUNY
description: Data mining and machine learning algorithms for biology, material design, social media analytics, emergency preparedness, wireless networks, and network science.
header: images/background.jpg
footer: images/background.jpg
proofer: false

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_research
  - scope:
      type: "research"
    values:
      layout: default
  # markdown files in /_grants
  - scope:
      type: "grants"
    values:
      layout: default
  # markdown files in /_software
  - scope:
      type: "software"
    values:
      layout: default
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # research project records
  research:
    output: false
  # grant records
  grants:
    output: false
  # software records
  software:
    output: false
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
