- id: arxiv:2309.09717
  type: paper
  link: https://arxiv.org/abs/2309.09717

- id: doi:10.1021/acsnano.2c05390
  type: paper
  link: https://pubs.acs.org/doi/full/10.1021/acsnano.2c05390

- id: doi:10.1145/3427384.3427386
  type: paper
  link: https://dl.acm.org/doi/10.1145/3427384.3427386

- id: doi:10.1109/INFCOMW.2018.8407002
  type: paper
  link: https://www.cs.albany.edu/~petko/lab/papers/zlsinfocomws2018.pdf

- id: doi:10.1063/1.5023258
  type: paper
  link: https://aip.scitation.org/doi/10.1063/1.5023258

- id: doi:10.1021/acsnano.8b03404
  type: paper
  link: https://pubs.acs.org/doi/abs/10.1021/acsnano.8b03404

- id: doi:10.1039/C8NR05781H
  type: paper
  link: https://pubs.rsc.org/en/content/articlelanding/2018/nr/c8nr05781h

- id: doi:10.1007/978-3-319-43513-8_2
  type: paper
  link: https://link.springer.com/chapter/10.1007/978-3-319-43513-8_2
